### ISSUE TITLE
Kafka Documentation page is broken

### ISSUE THREAD

**Issue by iamstavros** [mateusjunges/junges.dev#36]
https://junges.dev/documentation/laravel-kafka/v1.13/1-introduction

<img width="1365" alt="Screenshot 2024-04-08 at 11 40 53" src="https://github.com/mateusjunges/junges.dev/assets/152160825/e77f8d24-46ba-4294-8c69-8675685cdc0e">

**Comment by mateusjunges** [comment]
Just saw this issue. I fixed this a while ago, thanks for reporting!
